resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      slowCallDurationThreshold: 1500
      slowCallRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10000
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    backendA:
      baseConfig: default
    backendB:
      baseConfig: someShared